"""Phase 03 management-domain persistence foundation."""

from .domain import (
    BatchState,
    ManagementOperationType,
    OperationScopeKey,
    Priority,
    batch_content_is_editable,
    effective_priority,
    freeze_generation_parameters,
    is_archived,
    normalize_operation_scope_key,
    normalize_priority,
    operation_hash_matches,
    select_current_attempt,
)
from .models import (
    ManagementOperation,
    ProductionBatch,
    ProductionItem,
    ProductionItemAsset,
    ProductionItemAttempt,
    Project,
)
from .repository import (
    DraftAssetReference,
    DraftItem,
    ManagementConflictError,
    ManagementConstraintError,
    ManagementNotFoundError,
    ManagementRepository,
    ManagementRepositoryError,
    ManagementUnitOfWork,
    OperationMatch,
    OperationMatchKind,
)

__all__ = [
    "BatchState",
    "DraftAssetReference",
    "DraftItem",
    "ManagementConflictError",
    "ManagementConstraintError",
    "ManagementNotFoundError",
    "ManagementOperation",
    "ManagementOperationType",
    "ManagementRepository",
    "ManagementRepositoryError",
    "ManagementUnitOfWork",
    "OperationMatch",
    "OperationMatchKind",
    "OperationScopeKey",
    "Priority",
    "ProductionBatch",
    "ProductionItem",
    "ProductionItemAsset",
    "ProductionItemAttempt",
    "Project",
    "batch_content_is_editable",
    "effective_priority",
    "freeze_generation_parameters",
    "is_archived",
    "normalize_operation_scope_key",
    "normalize_priority",
    "operation_hash_matches",
    "select_current_attempt",
]
